export const TYPES = {
  EDITAR_RESTAURANTE_REQUEST: '@restaurante/EDITAR_RESTAURANTE_REQUEST',
  EDITAR_RESTAURANTE_SUCCESS: '@restaurante/EDITAR_RESTAURANTE_SUCCESS',
  EDITAR_RESTAURANTE_FAILED: '@restaurante/EDITAR_RESTAURANTE_FAILED',
};
