export const TYPES = {
  OBTER_TODOS_RESTAURANTES_REQUEST:
    '@restaurante/OBTER_TODOS_RESTAURANTES_REQUEST',
  OBTER_TODOS_RESTAURANTES_SUCCESS:
    '@restaurante/OBTER_TODOS_RESTAURANTES_SUCCESS',
  OBTER_TODOS_RESTAURANTES_FAILED:
    '@restaurante/OBTER_TODOS_RESTAURANTES_FAILED',

  OBTER_RESTAURANTE_REQUEST: '@restaurante/OBTER_RESTAURANTE_REQUEST',
  OBTER_RESTAURANTE_SUCCESS: '@restaurante/OBTER_RESTAURANTE_SUCCESS',
  OBTER_RESTAURANTE_FAILED: '@restaurante/OBTER_RESTAURANTE_FAILED',
};
