export const TYPES = {
  CRIAR_RESTAURANTE_REQUEST: '@restaurante/CRIAR_RESTAURANTE_REQUEST',
  CRIAR_RESTAURANTE_SUCCESS: '@restaurante/CRIAR_RESTAURANTE_SUCCESS',
  CRIAR_RESTAURANTE_FAILED: '@restaurante/CRIAR_RESTAURANTE_FAILED',
};
